apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service
  namespace: reference-service-showcase
  labels:
    app.kubernetes.io/name: reference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-service
    spec:
      containers:
        - name: reference-service
          image: chbatey/reference-service:latest
          ports:
            - containerPort: 8080
