apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: app-2
          image: paulbouwer/hello-kubernetes
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /
              port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-2
spec:
  rules:
    - host: app-2.local.mikesir87.training
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-20
              port: 
                number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
spec:
  selector:
    app: app-2
  ports:
    - port: 5000
