version: '3'
services:
  gradle_build:
    image: gradle:7.5.1-jdk17
    container_name: gradle_build
    volumes:
      - .:/opt/app
    working_dir: /opt/app

  service:
    container_name: service
    hostname: service
    environment:
      - DOWNSTREAM_HOST=podinfo
      - POSTGRES_HOST=database
    build:
      dockerfile: ./Dockerfile.service
    ports:
      - "8080:8080"
    depends_on:
      - "database"

  k6:
    image: grafana/k6
    volumes:
      - .:/opt/app
    working_dir: /opt/app

  downstream:
    container_name: podinfo
    hostname: podinfo
    image: stefanprodan/podinfo:6.2.2
    ports:
      - "9898:9898"

  database:
    container_name: database
    hostname: database
    image: 'postgres:15.0-bullseye'
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password

