apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3
spec:
  selector:
    matchLabels:
      app: app-3
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
        - name: app-3
          image: stefanprodan/podinfo:latest
          ports:
            - name: http
              containerPort: 9898
          resources:
            requests:
              memory: 20Mi
              cpu: 10m
            limits:
              memory: 20Mi
              cpu: 10m
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-3-ingress
spec:
  rules: 
     - host: app-3.tenant-b.cecg.local
       http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-3
                port:
                  name: http
---
apiVersion: v1
kind: Service
metadata:
  name: app-3
spec:
  selector:
    app: app-3
  ports:
  - name: http
    protocol: TCP
    port: 9898

