---
apiVersion: v1
kind: Service
metadata:
  name: app-10
  labels: 
    app: app-10
spec:
 ports:
  - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 8085
    targetPort: 8001
  selector: 
    app: app-10