
apiVersion: v1
kind: Service
metadata:
  name: database # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres

