kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-app-3  # Sets name of PVC
  labels:
    app: postgres
spec:
  volumeName: postgres-pv-volume
  storageClassName: ""
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 50Mi  # Sets volume size