apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
  namespace: reference-service-ci
spec:
  description: |
    cat-pr-readme takes a git repository and a PR number and
    prints the README.md file from that PR.
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: pr-number
      type: string
      description: The PR number to checkout
    - name: repo-name
      type: string
      description: The name of the repo
  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo
    - name: git-credentials
      description: SSH Keys
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
        - name: ssh-directory
          workspace: git-credentials
      params:
        - name: url
          value: $(params.repo-url)
        - name: refspec
          value: refs/pull/$(params.pr-number)/head
        - name: revision
          value: FETCH_HEAD
    - name: build
      runAfter: ["fetch-repo"]  # Wait until the clone is done before reading the readme.
      workspaces:
        - name: source
          workspace: shared-data
      taskSpec:
        workspaces:
          - name: source
        steps:
          - image: docker:20.10
            workingDir: $(workspaces.source.path)
            securityContext:
              privileged: true
            script: |
              apk add --update make
              pwd
              ls -ltr
              docker info
              make build
            volumeMounts:
             - mountPath: /var/run/
               name: dind-socket
        sidecars:
          - image: docker:20.10-dind
            name: docker
            securityContext:
              privileged: true
            readinessProbe:
              exec:
                command:
                  - ls
                  - /var/run/docker.sock
            volumeMounts:
              - mountPath: /var/lib/docker
                name: dind-storage
              - mountPath: /var/run/
                name: dind-socket
        volumes:
          - name: dind-storage
            emptyDir: { }
          - name: dind-socket
            emptyDir: { }
