apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-4
spec:
  selector:
    matchLabels:
      app: app-4
  template:
    metadata:
      labels:
        app: app-4
    spec:
      containers:
        - name: app-4
          image: paulbouwer/hello-kubernetes:1.10
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 500m

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-4
spec:
  rules:
    - host: app-4.local.mikesir87.training
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-4
              port: 
                number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-4
spec:
  selector:
    app: app-4
  ports:
    - port: 5000
