management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /internal
      exposure:
        include: status
  endpoint:
    status.enabled: true
    shutdown.enabled: false
  metrics.export.graphite.enabled: false



server:
  shutdown: GRACEFUL
  grace-period: 30s
  drainingMs: 10000
spring:
  lifecycle:
      timeout-per-shutdown-phase: 30s
