# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: team-a-monitoring
#   name: default-deny
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   - Egress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: team-a-monitoring
#   name: default-deny24
# spec:
#   podSelector: {}
#   policyTypes:
#   - Egress
#   egress:
#   # allow DNS resolution
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           name: app-1
# ---
# # apiVersion: networking.k8s.io/v1
# # kind: NetworkPolicy
# # metadata:
# #   namespace: app-1
# #   name: default-deny2434
# # spec:
# #   podSelector: {}
# #   policyTypes:
# #   - Ingress
# #   ingress:
# #   # allow DNS resolution
# #   - from:
# #     - namespaceSelector:
# #         matchLabels:
# #           name: team-a-monitoring
# # ---
# # apiVersion: networking.k8s.io/v1
# # kind: NetworkPolicy
# # metadata:
# #   namespace: team-a-monitoring
# #   name: default-deny243245
# # spec:
# #   podSelector: {}
# #   policyTypes:
# #   - Egress
# #   egress:
# #   # allow DNS resolution
# #   - to:
# #     - namespaceSelector:
# #         matchLabels:
# #           kubernetes.io/metadata.name: kube-system
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: team-a-monitoring
#   name: default-deny243245234
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   ingress:
#   # allow DNS resolution
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           name: app-4
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: team-a-monitoring
#   name: default-deny2432452341111
# spec:
#   podSelector: {}
#   policyTypes:
#   - Ingress
#   ingress:
#   # allow DNS resolution
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           name: team-a-monitoring
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   namespace: team-a-monitoring
#   name: default-deny2432452341111
# spec:
#   podSelector: {}
#   policyTypes:
#   - Egress
#   egress:
#   # allow DNS resolution
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           name: team-a-monitoring