apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: restrict-development-access
spec:
  namespaceSelector: 'name == "app-1"'
  ingress:
    - action: Allow
      source:
        namespaceSelector: 'name == "app-1"'
  egress:
    - action: Allow
      destination:
        namespaceSelector: 'name == "app-1"'