

{{- range .Values.org }}
{{- range $name, $values := . }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ $name }}
  name: {{ $name }}-default-deny-except-kube-dns
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
  policyTypes:
  - Egress
  - Ingress
---
{{ end }}
{{ end }}



{{- range .Values.org }}
{{- range $orgName, $orgValues := . }}
{{- range $orgValues.tenants}}
{{- range $tentantName , $tenantValue := .}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ $tentantName }}
  name: {{ $tentantName }}-default-deny-except-kube-dns
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
  policyTypes:
  - Egress
  - Ingress                                                                             
---
{{ end }}
{{ end }}
{{ end }}
{{ end }}


{{- range .Values.org }}
{{- range $orgName, $orgValues := . }}
{{- range $orgValues.tenants}}
{{- range $tentantName , $tenantValue := .}}
{{- range $subnsName := $tenantValue.subnamespaces}}

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ $subnsName.name }}
  name: {{ $subnsName.name }}-default-deny-except-kube-dns
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
  policyTypes:
  - Egress
  - Ingress                                                                             
---
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
