kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: cecg
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: team-a-monitoring
  name: foo-deny-egress
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: team-a-monitoring
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - namespaceSelector:
            matchLabels:
              name: app-1
    - to:
        - namespaceSelector:
            matchLabels:
              name: calico-apiserver
    - to:
        - namespaceSelector:
            matchLabels:
              name: calico-system
