


{{- range .Values.org }}
{{- range $orgName, $orgValues := . }}
{{- range $orgValues.tenants}}
{{- range $tentantName , $tenantValue := .}}
{{- range $subnsName := $tenantValue.subnamespaces}}
{{- range $subnsName.podLimits}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: {{ $subnsName.name }}
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: {{ $subnsName.podLimits.cpu }}
    memory: {{ $subnsName.podLimits.memory }}
---                                                                              
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}    