org:
 - cecg:
    flux:
      path: ./team-manifests/cecg
    tenants:
     - tenant-a:
        flux:
           path: ./team-manifests/tenant-a
        subnamespaces:
          - name: app-1
            flux:
              path: ./team-manifests/tenant-a/app-1
            podLimits:
               memory: 256Mi
               cpu:  500m
          - name: app-2
            flux:
              path: ./team-manifests/tenant-a/app-2
            podLimits:
               memory: 256Mi
               cpu:  500m
          - name: team-a-monitoring
            flux:
              path: ./team-manifests/tenant-a/team-a-monitoring/kube-prometheus-stack/
            podLimits:
               memory: 2048Mi
               cpu:  500m
     - tenant-b:
        flux:
           path: ./team-manifests/tenant-b
        subnamespaces:
         - name: team-b-monitoring
           flux:
              path: ./team-manifests/tenant-b/team-b-monitoring/kube-prometheus-stack/
           podLimits:
               memory: 2048Mi
               cpu:  500m 
         - name: app-4
           flux:
              path: ./team-manifests/tenant-b/app-4
           podLimits:
               memory: 256Mi
               cpu:  500m 
         - name: app-3
           flux:
              path: ./team-manifests/tenant-b/app-3
           podLimits:
               memory: 256Mi
               cpu:  500m 