
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-2  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "db-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-app-2  # Sets name of PVC
  labels:
    app: postgres
spec:
  volumeName: postgres-pv-volume-2
  storageClassName: ""
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 50Mi  # Sets volume size
