---
apiVersion: v1
kind: Service
metadata:
  annotations:
   prometheus.io/scrape: "true"
  name: reference
  labels: &labels
    app: reference-app
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.referenceport.serviceport }}
    targetPort: {{ .Values.referenceport.containerport }}
  - name: metrics
    protocol: TCP
    port: {{ .Values.metricsport.serviceport }}
    targetPort: {{ .Values.metricsport.containerport }}
  selector: *labels