apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-monitoring
spec:
  selector:
    matchLabels:
      app: team-a-monitoring
  template:
    metadata:
      labels:
        app: team-a-monitoring
    spec:
      containers:
        - name: team-a-monitoring
          image: paulbouwer/hello-kubernetes
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /
              port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-a-monitoring
spec:
  rules:
    - host: team-a-monitoring.local.mikesir87.training
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: team-a-monitoring0
              port: 
                number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: team-a-monitoring
spec:
  selector:
    app: team-a-monitoring
  ports:
    - port: 5000
